language: bash

services:
  - docker

before_script:
  - cp src/mysql/db.env.example src/mysql/db.env

script:
  - shellcheck *.sh
  - ./start.sh
  - docker ps | grep -q traefik
  - docker ps | grep -q sitename
  - docker ps | grep -q db
